package main

var SunAngleNames = map[int16]string{
	-179: "Geometric Sunset", // Sun's center at -0.83°
	-178: "Afterglow Peak",
	-177: "Final Limb Refraction",
	-176: "Evening Blue Hour",
	-175: "Earth's Shadow Rise",
	-174: "Civil Dusk", // Official Limit
	-173: "First Star Appearance",
	-172: "Terminator Departure",
	-171: "Last Terrestrial Color",
	-170: "Indigo Hour",
	-169: "Mariner's Last Light",
	-168: "Nautical Dusk", // Official Limit
	-167: "Horizon Line Obscurity",
	-166: "Deepening Gloom",
	-165: "Starlight Field Emergence",
	-164: "Last Crepuscular Glow",
	-163: "Milky Way Visibility",
	-162: "Astronomical Dusk", // Official Limit
	-161: "Nightfall",
	-160: "Last Zodiacal Light",
	-159: "Final Skyglow Fade",
	-158: "Deep Sky Revelation",
	-157: "Atmospheric Sodium Quiescence",
	-156: "First Umbral Touch",
	-155: "Night's Veil",
	-154: "Celestial Object Clarity",
	-153: "Deepening Nocturne",
	-152: "Airglow Becomes Visible",
	-151: "Stellar Field Dominance",
	-150: "Upper Astronomical Night",
	-149: "Nocturnal Stillness",
	-148: "Deep Sky Observation Window",
	-147: "Galactic Plane Visibility",
	-146: "Faint Light Pollution Becomes Apparent",
	-145: "Mid-Twilight's End",
	-144: "True Darkness Begins",
	-143: "Cimmerian Veil",
	-142: "Stygian Ascent",
	-141: "Erebus's Cloak",
	-140: "Lethean Shroud",
	-139: "Hadean Rise",
	-138: "Nocturnal Prime",
	-137: "Deep Night's Reign",
	-136: "Abyssal Ascent",
	-135: "Mid-Night Approach",
	-134: "Maximum Stellar Visibility",
	-133: "Galactic Core Transit",
	-132: "Deepest Sky Window",
	-131: "Zodiacal Band Visibility",
	-130: "Nocturnal Meridian",
	-129: "Atmospheric Transparency Peak",
	-128: "Gegenschein Apparition",
	-127: "Deepest Celestial View",
	-126: "Stellar Scintillation Minimum",
	-125: "Cosmic Ray Flux",
	-124: "Ionospheric Recombination",
	-123: "Magnetospheric Quiet",
	-122: "Deep Space Observation Climax",
	-121: "Terrestrial Shadow Apex",
	-120: "Two-Thirds Nadir Point",
	-119: "Geocoronal Glow",
	-118: "Interplanetary Dust Scatter",
	-117: "Faintest Observable Phenomena",
	-116: "Deep Night's Core",
	-115: "Maximum Darkness Approach",
	-114: "Sub-Horizon Nadir",
	-113: "Umbral Apex",
	-112: "Nocturnal Floor",
	-111: "Deepest Abyssal Point",
	-110: "Final Light Echoes Fade",
	-109: "Absolute Darkness Approach",
	-108: "Celestial Pole Zenith",
	-107: "Deepest Umbral Shadow",
	-106: "Pre-Nadir Stillness",
	-105: "Quarter-Nadir Point",
	-104: "Night's Lowest Ebb",
	-103: "Stygian Climax",
	-102: "Cimmerian Depth",
	-101: "Hadean Stillness",
	-100: "Lethean Void",
	-99:  "Erebus's Core",
	-98:  "Abyssal Floor",
	-97:  "Nocturnal Minimum Climax",
	-96:  "Umbral Nadir",
	-95:  "Deepest Night's Climax",
	-94:  "Nadiric Stillness",
	-93:  "Solar Opposition",
	-92:  "Gravitational Midpoint",
	-91:  "Nadir Imminence",
	-90:  "Solar Nadir",
	-89:  "Umbral Core",
	-88:  "Deepest Nocturne",
	-87:  "Stygian Stillness",
	-86:  "Cimmerian Void",
	-85:  "Hadean Obscurity",
	-84:  "Lethean Veil",
	-83:  "Erebus's Shroud",
	-82:  "Nocturnal Minimum",
	-81:  "Abyssal Point",
	-80:  "Deep Sky Zenith",
	-79:  "Galactic Meridian",
	-78:  "Maximum Starfield Contrast",
	-77:  "Faintest Skyglow Threshold",
	-76:  "Gegenschein Climax",
	-75:  "Pre-Dawn Obscurity",
	-74:  "Deep Night's Ebb",
	-73:  "Farthest Crepuscule",
	-72:  "Sub-Horizon Scatter",
	-71:  "Exospheric Refraction",
	-70:  "First Ionospheric Stirring",
	-69:  "Mesospheric Quiescence",
	-68:  "Noctilucent Cloud Floor",
	-67:  "Deep Twilight Approach",
	-66:  "Faint Zodiacal Arch",
	-65:  "Stellar Scintillation Peak",
	-64:  "Pre-Astronomical Gloom",
	-63:  "Celestial Pole Clarity",
	-62:  "Deepest Observable Magnitude",
	-61:  "Airglow Minimum",
	-60:  "Sub-Astronomical Limit",
	-59:  "Faint Light Cone",
	-58:  "Pre-Dawn's First Whisper",
	-57:  "Atmospheric Tide Turning",
	-56:  "High-Altitude Ozone Glow",
	-55:  "Deepest Indigo",
	-54:  "Vanishing Deep Sky Objects",
	-53:  "Fading Galactic Window",
	-52:  "First Hint of Dawn",
	-51:  "Subtle Horizon Lightening",
	-50:  "Astronomical Gloaming",
	-49:  "Faintest Crepuscular Ray",
	-48:  "Upper Mesospheric Scatter",
	-47:  "Sodium Layer Excitation",
	-46:  "First Stellar Fade",
	-45:  "Astronomical Twilight's Edge",
	-44:  "Deep Sky Obscuration",
	-43:  "Zodiacal Light Intensification",
	-42:  "Pre-Nautical Obscurity",
	-41:  "Fading Starlight",
	-40:  "Celestial Equator Glow",
	-39:  "Horizon's First Definition",
	-38:  "Deep Sapphire Hue",
	-37:  "Mariner's First Horizon",
	-36:  "False Dawn",
	-35:  "Primary Crepuscular Arch",
	-34:  "Nautical Gloaming",
	-33:  "First Navigational Light",
	-32:  "Deep Blue Transition",
	-31:  "Horizon Illumination",
	-30:  "Upper Nautical Twilight",
	-29:  "Pre-Civil Glow",
	-28:  "Sky-Sea Line Clarity",
	-27:  "First Color Temperature Shift",
	-26:  "Indigo Fades to Cobalt",
	-25:  "First Silhouette Visibility",
	-24:  "Early Alpenglow",
	-23:  "Initial Belt of Venus",
	-22:  "First Terrestrial Definition",
	-21:  "Shadow Line Approach",
	-20:  "Pre-Dawn Radiance",
	-19:  "Last Astrometric Point",
	-18:  "Astronomical Dawn", // Official Limit
	-17:  "Faint Sky Brightening",
	-16:  "Early Nautical Twilight",
	-15:  "Horizon Definition",
	-14:  "Mariner's Light",
	-13:  "Deep Indigo Sky",
	-12:  "Nautical Dawn", // Official Limit
	-11:  "Early Blue Hour",
	-10:  "First Light",
	-9:   "Terminator Passage",
	-8:   "Alpenglow Peak",
	-7:   "Belt of Venus Apex",
	-6:   "Civil Dawn", // Official Limit
	-5:   "Blue Hour",
	-4:   "Early Golden Hour",
	-3:   "Solar Disc Apparition",
	-2:   "First Direct Scintillation",
	-1:   "Geometric Sunrise", // Sun's center at -0.83°
	0:    "Apparent Sunrise",  // Upper limb on horizon
	1:    "Upper Limb Clearance",
	2:    "Daybreak Radiance",
	3:    "Low-Angle Illumination",
	4:    "Rayleigh Scattering Dominance",
	5:    "Warm Spectrum Saturation",
	6:    "Golden Hour Apex", // End of core Golden Hour
	7:    "Morning Clarity",
	8:    "Matutinal Period",
	9:    "Shadows Begin to Shorten",
	10:   "Increasing Insolation",
	11:   "Dew Point Evaporation",
	12:   "Cool Spectrum Emergence",
	13:   "Ascending Arc Illumination",
	14:   "Daylight Normalization",
	15:   "Early Morning Prime",
	16:   "Atmospheric Haze Burn-off",
	17:   "Photosynthesis Acceleration",
	18:   "Solar Angle Growth",
	19:   "Morning Thermal Lift",
	20:   "Chromatic Neutrality",
	21:   "Post-Dawn Transition",
	22:   "Short-Wave Radiation Increase",
	23:   "Daylight Intensity Climb",
	24:   "Azimuthal Advance",
	25:   "Ante Meridiem Ascent",
	26:   "Light Polarization Shift",
	27:   "Mid-Morning Approach",
	28:   "Shadow Edge Sharpening",
	29:   "Growing Radiance",
	30:   "Quarter-Zenith Point",
	31:   "Solar Energy Flux Growth",
	32:   "Atmospheric Window Clarity",
	33:   "UV-B Radiation Begins",
	34:   "High-Contrast Illumination",
	35:   "Atmospheric Filtering Diminishes",
	36:   "Mid-Morning Period",
	37:   "Convective Currents Rise",
	38:   "Light Intensity Plateauing",
	39:   "Sub-Apical Climb",
	40:   "UV-A Index Intensification",
	41:   "Near-Noon Brilliance",
	42:   "Shadow Contraction",
	43:   "Maximum Photosynthetic Rate",
	44:   "High Solar Arc",
	45:   "Half-Zenith Angle",
	46:   "Pre-Culmination Phase",
	47:   "Sky Brightness Peak",
	48:   "Solar Disc Glare",
	49:   "Approaching Meridian",
	50:   "High-Insolation Period",
	51:   "Thermal Maximum Approach",
	52:   "Shortest Shadow Approach",
	53:   "Sub-Zenithal Position",
	54:   "Direct Overhead Radiation",
	55:   "Near-Apical Point",
	56:   "Atmospheric Refraction Minimum",
	57:   "Light Ray Perpendicularity",
	58:   "Pre-Noon Climax",
	59:   "Zenithal Incline",
	60:   "Two-Thirds Zenith Point",
	61:   "Maximum Irradiance Approach",
	62:   "Solar Flux Concentration",
	63:   "Near-Meridian Transit",
	64:   "High-Energy Photon Flux",
	65:   "Peak UV Index",
	66:   "Sub-Culmination",
	67:   "Azimuthal Slowdown",
	68:   "Minimum Atmospheric Path",
	69:   "Zenithal Brilliance",
	70:   "Approaching Solar Apex",
	71:   "Shadow Boundary Fading",
	72:   "Peak Luminosity",
	73:   "High-Angle Insolation",
	74:   "Near-Perpendicular Illumination",
	75:   "Culmination Imminent",
	76:   "Solar Meridian Proximity",
	77:   "Zenithal Corona",
	78:   "Maximum Light Intensity",
	79:   "Apical Point Proximity",
	80:   "Near-Zenith",
	81:   "Shadow Vanishing Point",
	82:   "Peak Solar Energy",
	83:   "Direct Overhead Transit",
	84:   "Minimum Shadow Convergence",
	85:   "Zenithal Climax",
	86:   "Meridian Crossing Imminent",
	87:   "Sub-Zenithal Stillness",
	88:   "Perpendicular Illumination",
	89:   "Zenith Imminence",
	90:   "Solar Noon", // Maximum Elevation
	91:   "Post-Meridian Decline",
	92:   "Zenithal Departure",
	93:   "Declining Solar Arc",
	94:   "Perpendicularity Lost",
	95:   "Waning Zenithal Climax",
	96:   "Shadow Re-emergence",
	97:   "Post-Apical Transit",
	98:   "Decreasing Solar Energy",
	99:   "Fading Overhead Brilliance",
	100:  "Post-Zenith Period",
	101:  "Maximum Luminosity Passed",
	102:  "Waning Light Intensity",
	103:  "Departing Solar Meridian",
	104:  "Culmination's Wake",
	105:  "High-Angle Decline",
	106:  "Waning Luminosity",
	107:  "Shadow Boundary Growth",
	108:  "Departing Solar Apex",
	109:  "Atmospheric Path Lengthens",
	110:  "Azimuthal Acceleration",
	111:  "Sub-Culmination Descent",
	112:  "Declining UV Index",
	113:  "High-Energy Flux Decrease",
	114:  "Post-Meridian Flux",
	115:  "Waning Irradiance",
	116:  "Two-Thirds Zenith Descent",
	117:  "Solar Flux Diffusion",
	118:  "Light Ray Obliquity",
	119:  "Atmospheric Refraction Increase",
	120:  "Post-Noon Period",
	121:  "Thermal Maximum Passed",
	122:  "Sub-Zenithal Decline",
	123:  "Shadow Elongation",
	124:  "Direct Radiation Decrease",
	125:  "Afternoon Brilliance",
	126:  "UV-A Index Decline",
	127:  "Light Intensity Softening",
	128:  "Descending High Arc",
	129:  "Mid-Afternoon Approach",
	130:  "Half-Zenith Descent",
	131:  "High-Insolation Ends",
	132:  "Sky Brightness Softens",
	133:  "Pre-Golden Hour Phase",
	134:  "Shadow Projection",
	135:  "Afternoon Prime",
	136:  "Convective Currents Subside",
	137:  "Light Polarization Reversal",
	138:  "Chromatic Shift Begins",
	139:  "Daylight Intensity Wanes",
	140:  "Short-Wave Radiation Decline",
	141:  "Post-Meridiem Descent",
	142:  "Azimuthal Westward Shift",
	143:  "Light Spectrum Warms",
	144:  "Late Afternoon Period",
	145:  "Atmospheric Filtering Increases",
	146:  "Low-Contrast Illumination",
	147:  "UV-B Radiation Ends",
	148:  "Shadow Definition Softens",
	149:  "Waning Radiance",
	150:  "Quarter-Zenith Descent",
	151:  "Pre-Vesperal Light",
	152:  "Photosynthesis Slowdown",
	153:  "Atmospheric Haze Reappears",
	154:  "Daylight Normalization Ends",
	155:  "Descending Arc Glow",
	156:  "Cool Spectrum Fades",
	157:  "Shadows Begin to Merge",
	158:  "Matutinal Period's End",
	159:  "Golden Hour Imminent",
	160:  "Warm Spectrum Re-emergence",
	161:  "Rayleigh Scatter Intensifies",
	162:  "Low-Angle Diffusion",
	163:  "Chiaroscuro Evening",
	164:  "Vesperal Radiance",
	165:  "Late Afternoon Glow",
	166:  "Hesperian Light",
	167:  "Long Shadow Period",
	168:  "Final Thermal Lift",
	169:  "Pre-Sunset Transition",
	170:  "Vesperal Spectrum Shift",
	171:  "Evening Clarity",
	172:  "Final Golden Hour",
	173:  "Sunset Radiance",
	174:  "Evening Golden Hour", // Start of core Golden Hour
	175:  "Solar Disc Immersion",
	176:  "Green Flash Window",
	177:  "Lower Limb Contact",
	178:  "Final Direct Scintillation",
	179:  "Upper Limb Disappearance",
	180:  "Apparent Sunset", // Upper limb on horizon
}
